# Define base image (example: alpine:3.7)
FROM alpine:3.7

# Write your build logic here.

# Define entrypoint (uncomment) (optional, if not defined, then sh binary will be used)
# ENTRYPOINT [ "executable" ]

# Define starting arguments/cmd
CMD [ "executable" ]