# Install Docker Community Edition for Centos 7x

- hosts: swarm

  vars_prompt:

    - name: "timeserver1"
      prompt: "Primary timeserver ip"
      default: "0.fi.pool.ntp.org"
      private: no

    - name: "timeserver2"
      prompt: "Secondary timeserver ip"
      default: "1.fi.pool.ntp.org"
      private: no

  tasks:

    # Remove old Docker versions and metadata

    - name: Install chrony
      shell: yum -y install chrony
      become: true

    - template:
        src: configurations/chrony/chrony.conf
        dest: /etc/chrony.conf
        owner: root
        group: root
        mode: 0644

    - name: Enable chronyd
      shell: systemctl enable chronyd
      become: true
    
    - name: Start chronyd
      shell: systemctl start chronyd
      become: true